INSERT INTO employees  (first_name, last_name, email, department, job_title) 
VALUES 
('Editha', 'Spataro', 'espataro0@dot.gov', 'Marketing', 'Speech Pathologist');
('Ketty', 'Marquez', 'kmarquez1@timesonline.co.uk', 'Support', 'Senior Cost Accountant');
('Nickie', 'Pieter', 'npieter2@hc360.com', 'Business Development', 'Programmer Analyst IV');
('Clare', 'Newman', 'cnewman3@opera.com', 'Training', 'Speech Pathologist');
('Hadley', 'Tudball', 'htudball4@si.edu', 'Product Management', 'Environmental Tech');
('Mahala', 'Langeren', 'mlangeren5@sakura.ne.jp', 'Research and Development', 'Web Developer III');
('Grove', 'Neagle', 'gneagle6@japanpost.jp', 'Sales', 'Clinical Specialist');
('Mathias', 'Mosley', 'mmosley7@pcworld.com', 'Product Management', 'Programmer II');
('Worden', 'Hinrichsen', 'whinrichsen8@bing.com', 'Training', 'Automation Specialist III');
('Eba', 'Ramme', 'eramme9@army.mil', 'Product Management', 'Budget/Accounting Analyst IV');
('Joseito', 'Helleckas', 'jhelleckasa@cpanel.net', 'Engineering', 'Administrative Assistant I');
('Arden', 'Izac', 'aizacb@deliciousdays.com', 'Marketing', 'Assistant Professor');
('Alma', 'Titley', 'atitleyc@apache.org', 'Sales', 'Structural Engineer');
('Nickolai', 'Nayshe', 'nnayshed@lulu.com', 'Accounting', 'Structural Engineer');
('Tallou', 'Drake', 'tdrakee@soup.io', 'Product Management', 'Recruiting Manager');
('Yance', 'Gargett', 'ygargettf@omniture.com', 'Research and Development', 'Programmer Analyst IV');
('Jakob', 'Seligson', 'jseligsong@examiner.com', 'Accounting', 'GIS Technical Architect');
('Brittni', 'Alfwy', 'balfwyh@psu.edu', 'Legal', 'Technical Writer');
('Syman', 'Shipcott', 'sshipcotti@usatoday.com', 'Legal', 'Administrative Assistant I');
('Delmer', 'Demogeot', 'ddemogeotj@infoseek.co.jp', 'Sales', 'Senior Editor');
('Selena', 'Woolmer', 'swoolmerk@mail.ru', 'Research and Development', 'Web Designer I');
('Claiborn', 'Jaray', 'cjarayl@networkadvertising.org', 'Human Resources', 'General Manager');
('Louisa', 'Caffrey', 'lcaffreym@prweb.com', 'Sales', 'Social Worker');
('Garfield', 'Marusik', 'gmarusikn@tripadvisor.com', 'Product Management', 'Product Engineer');
('Reina', 'Arpino', 'rarpinoo@ow.ly', 'Human Resources', 'Junior Executive');
('Cheston', 'Symmons', 'csymmonsp@dyndns.org', 'Sales', 'Staff Scientist');
('Barbette', 'Fayers', 'bfayersq@constantcontact.com', 'Product Management', 'Financial Analyst');
('Clarence', 'Keedy', 'ckeedyr@weebly.com', 'Product Management', 'Speech Pathologist');
('Harp', 'Nutman', 'hnutmans@yahoo.com', 'Research and Development', 'Marketing Assistant');
('Frederigo', 'Dumini', 'fduminit@miibeian.gov.cn', 'Engineering', 'Nurse');
('Gilly', 'Wagstaff', 'gwagstaffu@redcross.org', 'Product Management', 'Internal Auditor');
('Murry', 'Petrusch', 'mpetruschv@google.com', 'Sales', 'Dental Hygienist');
('Cammy', 'Garden', 'cgardenw@ocn.ne.jp', 'Support', 'Food Chemist');
('Adeline', 'Bogges', 'aboggesx@blogspot.com', 'Research and Development', 'Administrative Officer');
('Kath', 'Totton', 'ktottony@xing.com', 'Services', 'Marketing Manager');
('Van', 'Rainer', 'vrainerz@google.ru', 'Accounting', 'VP Quality Control');
('Austen', 'Withams', 'awithams10@cloudflare.com', 'Legal', 'Senior Quality Engineer');
('Betteanne', 'Sisson', 'bsisson11@economist.com', 'Product Management', 'General Manager');
('Anders', 'Mordue', 'amordue12@globo.com', 'Research and Development', 'Data Coordiator');
('Barbie', 'Cookley', 'bcookley13@hp.com', 'Research and Development', 'Nurse Practicioner');
('Milty', 'Virgoe', 'mvirgoe14@sbwire.com', 'Accounting', 'Developer IV');
('Joann', 'Hallum', 'jhallum15@discovery.com', 'Engineering', 'Biostatistician IV');
('Emmaline', 'Pieterick', 'epieterick16@so-net.ne.jp', 'Services', 'Associate Professor');
('Miltie', 'Brownsworth', 'mbrownsworth17@amazonaws.com', 'Services', 'General Manager');
('Hermann', 'Wonter', 'hwonter18@tmall.com', 'Legal', 'Structural Analysis Engineer');
('Joline', 'Gligori', 'jgligori19@devhub.com', 'Training', 'Human Resources Manager');
('Wanda', 'Oldham', 'woldham1a@freewebs.com', 'Research and Development', 'Senior Quality Engineer');
('Rolando', 'Gramer', 'rgramer1b@vkontakte.ru', 'Support', 'VP Accounting');
('Udale', 'Crumbie', 'ucrumbie1c@howstuffworks.com', 'Marketing', 'Research Assistant IV');
('Trudi', 'Slayny', 'tslayny1d@seattletimes.com', 'Engineering', 'Developer II');
('Joelle', 'Gilders', 'jgilders1e@discuz.net', 'Services', 'Social Worker');
('Codee', 'Amesbury', 'camesbury1f@soundcloud.com', 'Services', 'Recruiter');
('Izzy', 'Penhearow', 'ipenhearow1g@engadget.com', 'Services', 'Financial Analyst');
('Brittani', 'Everton', 'beverton1h@skype.com', 'Business Development', 'Safety Technician III');
('Maurizio', 'Fowley', 'mfowley1i@mayoclinic.com', 'Legal', 'Budget/Accounting Analyst IV');
('Delphinia', 'Danzig', 'ddanzig1j@mapy.cz', 'Engineering', 'Automation Specialist IV');
('Chrissie', 'Biggin', 'cbiggin1k@ihg.com', 'Research and Development', 'Senior Quality Engineer');
('Linet', 'Paprotny', 'lpaprotny1l@topsy.com', 'Legal', 'Internal Auditor');
('Claudetta', 'Ambrogelli', 'cambrogelli1m@squidoo.com', 'Human Resources', 'Senior Cost Accountant');
('Rasla', 'Stredder', 'rstredder1n@answers.com', 'Support', 'Nurse');
('Ivory', 'Corcoran', 'icorcoran1o@bandcamp.com', 'Engineering', 'Social Worker');
('Brynn', 'Sottell', 'bsottell1p@bravesites.com', 'Product Management', 'Account Executive');
('Jervis', 'Askham', 'jaskham1q@prweb.com', 'Human Resources', 'Recruiting Manager');
('Celine', 'Dobrowlski', 'cdobrowlski1r@etsy.com', 'Research and Development', 'Staff Accountant II');
('Jean', 'Van den Oord', 'jvandenoord1s@homestead.com', 'Product Management', 'Account Representative III');
('Barry', 'Fishleigh', 'bfishleigh1t@usgs.gov', 'Accounting', 'Environmental Specialist');
('Joel', 'Bloss', 'jbloss1u@w3.org', 'Sales', 'Human Resources Manager');
('Teirtza', 'Platts', 'tplatts1v@cafepress.com', 'Engineering', 'Electrical Engineer');
('Alisander', 'Rosenstein', 'arosenstein1w@hatena.ne.jp', 'Human Resources', 'Accounting Assistant IV');
('Gisele', 'Robecon', 'grobecon1x@twitter.com', 'Training', 'Project Manager');
('Sigmund', 'Dignon', 'sdignon1y@altervista.org', 'Business Development', 'VP Accounting');
('Daniela', 'Amorine', 'damorine1z@seattletimes.com', 'Research and Development', 'Media Manager III');
('Lind', 'Rissen', 'lrissen20@shinystat.com', 'Research and Development', 'Director of Sales');
('Adrien', 'Lowings', 'alowings21@sohu.com', 'Business Development', 'Speech Pathologist');
('Shaun', 'Lordon', 'slordon22@reddit.com', 'Services', 'Compensation Analyst');
('Elisa', 'Eixenberger', 'eeixenberger23@senate.gov', 'Engineering', 'Senior Sales Associate');
('Kali', 'Coltart', 'kcoltart24@weibo.com', 'Accounting', 'GIS Technical Architect');
('Charley', 'Jorez', 'cjorez25@is.gd', 'Marketing', 'Electrical Engineer');
('Hastie', 'Oslar', 'hoslar26@chron.com', 'Training', 'VP Product Management');
('Simone', 'Netherwood', 'snetherwood27@indiatimes.com', 'Engineering', 'Business Systems Development Analyst');
('Leonanie', 'Gingles', 'lgingles28@merriam-webster.com', 'Product Management', 'Cost Accountant');
('Jordan', 'Sex', 'jsex29@theguardian.com', 'Support', 'Senior Sales Associate');
('Jonah', 'Cobello', 'jcobello2a@bigcartel.com', 'Accounting', 'Administrative Assistant II');
('Lucretia', 'Attenbarrow', 'lattenbarrow2b@statcounter.com', 'Marketing', 'Health Coach II');
('Johnath', 'Grayham', 'jgrayham2c@yahoo.com', 'Accounting', 'Software Engineer I');
('Berri', 'Le feuvre', 'blefeuvre2d@intel.com', 'Research and Development', 'Programmer Analyst IV');
('Leonid', 'Hof', 'lhof2e@craigslist.org', 'Product Management', 'Senior Financial Analyst');
('Twyla', 'Bonhan', 'tbonhan2f@icio.us', 'Product Management', 'Editor');
('Claudie', 'Ventham', 'cventham2g@about.com', 'Product Management', 'Graphic Designer');
('Maris', 'Faloon', 'mfaloon2h@bloomberg.com', 'Support', 'Recruiting Manager');
('Kahlil', 'Plaskitt', 'kplaskitt2i@i2i.jp', 'Research and Development', 'Product Engineer');
('Burg', 'Treeby', 'btreeby2j@twitpic.com', 'Training', 'Accountant III');
('Mersey', 'Jarret', 'mjarret2k@wisc.edu', 'Services', 'Help Desk Operator');
('Grantham', 'Langsdon', 'glangsdon2l@washingtonpost.com', 'Sales', 'Tax Accountant');
('Cody', 'Wabe', 'cwabe2m@cnbc.com', 'Support', 'Senior Sales Associate');
('Niven', 'Brittlebank', 'nbrittlebank2n@mayoclinic.com', 'Sales', 'Automation Specialist I');
('Maia', 'Licas', 'mlicas2o@stanford.edu', 'Business Development', 'Speech Pathologist');
('Estrella', 'Gillingham', 'egillingham2p@blogs.com', 'Accounting', 'Electrical Engineer');
('Bambi', 'Goss', 'bgoss2q@ihg.com', 'Product Management', 'Food Chemist');
('Ingemar', 'Aggus', 'iaggus2r@jigsy.com', 'Legal', 'Technical Writer');
('Joe', 'Possell', 'jpossell2s@networksolutions.com', 'Human Resources', 'Research Nurse');
('Jeffry', 'Chanson', 'jchanson2t@globo.com', 'Sales', 'Research Assistant I');
('Isaiah', 'Flitcroft', 'iflitcroft2u@macromedia.com', 'Research and Development', 'Health Coach I');
('Myrvyn', 'Gibb', 'mgibb2v@squarespace.com', 'Research and Development', 'Registered Nurse');
('Claybourne', 'Giovani', 'cgiovani2w@topsy.com', 'Training', 'Librarian');
('Woody', 'Hucks', 'whucks2x@independent.co.uk', 'Human Resources', 'Recruiter');
('Nada', 'Hansard', 'nhansard2y@latimes.com', 'Support', 'Senior Developer');
('Renata', 'Straniero', 'rstraniero2z@g.co', 'Human Resources', 'Computer Systems Analyst III');
('Jordana', 'Simonot', 'jsimonot30@arstechnica.com', 'Research and Development', 'Actuary');
('Eolande', 'Mushrow', 'emushrow31@prnewswire.com', 'Support', 'Health Coach II');
('Florella', 'Gregson', 'fgregson32@aboutads.info', 'Marketing', 'Media Manager III');
('Karlen', 'Summerlad', 'ksummerlad33@biblegateway.com', 'Research and Development', 'Structural Analysis Engineer');
('Melvyn', 'Barthorpe', 'mbarthorpe34@nymag.com', 'Research and Development', 'Account Representative IV');
('Sissie', 'Heales', 'sheales35@google.com', 'Legal', 'Nurse Practicioner');
('Winslow', 'Kippins', 'wkippins36@comsenz.com', 'Business Development', 'Product Engineer');
('Leland', 'Darbon', 'ldarbon37@fastcompany.com', 'Accounting', 'Recruiter');
('Frankie', 'Kettlesting', 'fkettlesting38@disqus.com', 'Product Management', 'Information Systems Manager');
('Patsy', 'Webberley', 'pwebberley39@joomla.org', 'Research and Development', 'Administrative Assistant II');
('Marian', 'Bagniuk', 'mbagniuk3a@time.com', 'Business Development', 'Electrical Engineer');
('Marcile', 'Mundford', 'mmundford3b@mit.edu', 'Accounting', 'Safety Technician II');
('Dedra', 'Spillane', 'dspillane3c@huffingtonpost.com', 'Services', 'Operator');
('Henrik', 'Noden', 'hnoden3d@ebay.co.uk', 'Support', 'Food Chemist');
('Tann', 'Godbert', 'tgodbert3e@sakura.ne.jp', 'Services', 'Senior Quality Engineer');
('Lorita', 'Nagle', 'lnagle3f@hhs.gov', 'Research and Development', 'Information Systems Manager');
('Hugo', 'Burges', 'hburges3g@cbslocal.com', 'Marketing', 'Chemical Engineer');
('Claudio', 'Easlea', 'ceaslea3h@google.co.jp', 'Business Development', 'Staff Scientist');
('Sergei', 'Oakwell', 'soakwell3i@ifeng.com', 'Marketing', 'Nurse Practicioner');
('Nona', 'Splevings', 'nsplevings3j@fda.gov', 'Engineering', 'Senior Developer');
('Bibi', 'Quick', 'bquick3k@taobao.com', 'Engineering', 'Quality Engineer');
('Elton', 'Barrow', 'ebarrow3l@uiuc.edu', 'Legal', 'Help Desk Technician');
('Emmanuel', 'Speir', 'espeir3m@acquirethisname.com', 'Research and Development', 'Software Consultant');
('Fredelia', 'Turrell', 'fturrell3n@hc360.com', 'Research and Development', 'Paralegal');
('Maxy', 'Dorbon', 'mdorbon3o@tiny.cc', 'Support', 'Senior Editor');
('Holt', 'Sewley', 'hsewley3p@gov.uk', 'Business Development', 'Chief Design Engineer');
('Lyndsie', 'Taverner', 'ltaverner3q@photobucket.com', 'Accounting', 'Engineer IV');
('Melli', 'Mossman', 'mmossman3r@usgs.gov', 'Sales', 'Geologist III');
('Mahmud', 'd'' Eye', 'mdeye3s@apache.org', 'Product Management', 'Payment Adjustment Coordinator');
('Sharity', 'Sinclar', 'ssinclar3t@free.fr', 'Legal', 'Sales Associate');
('Donal', 'McFarlane', 'dmcfarlane3u@arizona.edu', 'Business Development', 'Software Engineer II');
('Roanna', 'Danzig', 'rdanzig3v@constantcontact.com', 'Business Development', 'Junior Executive');
('Abelard', 'Yearns', 'ayearns3w@desdev.cn', 'Marketing', 'Senior Sales Associate');
('Valencia', 'Yoxen', 'vyoxen3x@bluehost.com', 'Research and Development', 'Software Consultant');
('Constantina', 'Grahame', 'cgrahame3y@issuu.com', 'Business Development', 'Senior Editor');
('Lark', 'Dawbery', 'ldawbery3z@reddit.com', 'Marketing', 'Account Coordinator');
('Maure', 'Hannah', 'mhannah40@arizona.edu', 'Research and Development', 'Professor');
('Hadrian', 'Ware', 'hware41@who.int', 'Sales', 'Help Desk Technician');
('Rafa', 'Lamberton', 'rlamberton42@psu.edu', 'Legal', 'VP Quality Control');
('Aile', 'Kingzeth', 'akingzeth43@tamu.edu', 'Legal', 'Administrative Officer');
('Erda', 'Salery', 'esalery44@sakura.ne.jp', 'Services', 'Senior Quality Engineer');
('Dixie', 'Tizard', 'dtizard45@ca.gov', 'Training', 'Actuary');
('Shalne', 'Ogilvy', 'sogilvy46@hugedomains.com', 'Sales', 'Structural Engineer');
('Lemuel', 'Marsters', 'lmarsters47@ocn.ne.jp', 'Training', 'Accountant III');
('Milissent', 'Castellani', 'mcastellani48@nbcnews.com', 'Legal', 'Programmer Analyst II');
('Adah', 'Creech', 'acreech49@ifeng.com', 'Research and Development', 'Human Resources Manager');
('Rodolphe', 'Kryzhov', 'rkryzhov4a@ted.com', 'Product Management', 'Software Engineer III');
('Eliza', 'Braunton', 'ebraunton4b@360.cn', 'Marketing', 'Data Coordiator');
('Leola', 'Sorrel', 'lsorrel4c@berkeley.edu', 'Training', 'Systems Administrator I');
('Karl', 'McEntagart', 'kmcentagart4d@techcrunch.com', 'Sales', 'Librarian');
('Karee', 'Karchewski', 'kkarchewski4e@washington.edu', 'Services', 'Research Assistant IV');
('Jeri', 'Callander', 'jcallander4f@shutterfly.com', 'Research and Development', 'Staff Accountant I');
('Alyosha', 'Staterfield', 'astaterfield4g@blogspot.com', 'Engineering', 'Assistant Manager');
('Jelene', 'Rubra', 'jrubra4h@stumbleupon.com', 'Human Resources', 'GIS Technical Architect');
('Clio', 'Volks', 'cvolks4i@biblegateway.com', 'Sales', 'Sales Associate');
('Emmett', 'Koba', 'ekoba4j@clickbank.net', 'Research and Development', 'Design Engineer');
('Worden', 'Gummie', 'wgummie4k@freewebs.com', 'Human Resources', 'Staff Scientist');
('Gregorius', 'Gabb', 'ggabb4l@nba.com', 'Support', 'Geologist II');
('Elfrieda', 'Bradburne', 'ebradburne4m@independent.co.uk', 'Business Development', 'Financial Advisor');
('Malanie', 'Chipps', 'mchipps4n@sfgate.com', 'Business Development', 'Technical Writer');
('Amandie', 'Lidierth', 'alidierth4o@ucoz.ru', 'Business Development', 'Nurse Practicioner');
('Gualterio', 'Gobourn', 'ggobourn4p@deviantart.com', 'Services', 'Recruiting Manager');
('Cory', 'Huster', 'chuster4q@lulu.com', 'Legal', 'Sales Associate');
('Ramon', 'Morton', 'rmorton4r@twitter.com', 'Product Management', 'Marketing Assistant');
('Emanuel', 'Sand', 'esand4s@unblog.fr', 'Business Development', 'Database Administrator I');
('Winston', 'Lankford', 'wlankford4t@4shared.com', 'Engineering', 'Staff Scientist');
('Sigfried', 'Raffon', 'sraffon4u@clickbank.net', 'Accounting', 'Design Engineer');
('Richmond', 'Greatbatch', 'rgreatbatch4v@networksolutions.com', 'Marketing', 'Accounting Assistant II');
('Wilburt', 'Zamboniari', 'wzamboniari4w@slideshare.net', 'Legal', 'Programmer IV');
('Julie', 'Dennison', 'jdennison4x@timesonline.co.uk', 'Support', 'Research Assistant IV');
('Cheston', 'Boland', 'cboland4y@etsy.com', 'Accounting', 'Environmental Tech');
('Aldin', 'Iannello', 'aiannello4z@webnode.com', 'Marketing', 'Physical Therapy Assistant');
('Christi', 'Kennifick', 'ckennifick50@webnode.com', 'Sales', 'Media Manager III');
('Dorine', 'Royden', 'droyden51@cloudflare.com', 'Engineering', 'Assistant Professor');
('Cole', 'Igonet', 'cigonet52@princeton.edu', 'Sales', 'Research Associate');
('Sasha', 'Milby', 'smilby53@mayoclinic.com', 'Training', 'Media Manager III');
('Reggie', 'Godard', 'rgodard54@independent.co.uk', 'Services', 'Project Manager');
('Gerda', 'Dyte', 'gdyte55@ox.ac.uk', 'Human Resources', 'Geological Engineer');
('Corabella', 'Seers', 'cseers56@washingtonpost.com', 'Human Resources', 'Programmer II');
('Elia', 'MacGillavery', 'emacgillavery57@scribd.com', 'Marketing', 'Cost Accountant');
('Kellyann', 'Kinavan', 'kkinavan58@seesaa.net', 'Sales', 'Accounting Assistant II');
('Cortney', 'Novotna', 'cnovotna59@amazon.de', 'Accounting', 'Internal Auditor');
('Greg', 'Aymer', 'gaymer5a@usnews.com', 'Marketing', 'Product Engineer');
('Obadias', 'Blazi', 'oblazi5b@nymag.com', 'Accounting', 'Geological Engineer');
('Aile', 'Schukert', 'aschukert5c@eventbrite.com', 'Sales', 'Community Outreach Specialist');
('Laughton', 'Leynton', 'lleynton5d@redcross.org', 'Business Development', 'Dental Hygienist');
('Druci', 'Kleimt', 'dkleimt5e@tinypic.com', 'Product Management', 'Software Engineer IV');
('Judith', 'MacConneely', 'jmacconneely5f@artisteer.com', 'Services', 'VP Sales');
('Grannie', 'Flux', 'gflux5g@timesonline.co.uk', 'Services', 'Financial Analyst');
('Petunia', 'Lillyman', 'plillyman5h@examiner.com', 'Product Management', 'Senior Sales Associate');
('Sylvia', 'Katte', 'skatte5i@bloomberg.com', 'Human Resources', 'Paralegal');
('Collen', 'Rowden', 'crowden5j@aboutads.info', 'Human Resources', 'Pharmacist');
