    -- id INTEGER NOT NULL AUTO_INCREMENT,
    -- first_name VARCHAR(50) NOT NULL,
    -- last_name VARCHAR(50) NOT NULL,
    -- email VARCHAR(50) NOT NULL,
    -- job_title VARCHAR(50) NOT NULL,
    -- fk_department INT NOT NULL,
    -- fk_job_title INT NOT NULL,

-- Just as I need to create the departments first, I need to do the same with the creation of these employee seeds. They will have integers as foreign keys to represent their department and job titles.
INSERT INTO departments (department_name)
VALUES
('Research and Development'),
('Human Resources'),
('Services'),
('Accounting'),
('Sales'),
('Silly Walks'),
('Putting Things On Top of Other Things'),
('Product Management');

INSERT INTO job_titles (job_title, salary, job_description, department)
VALUES
('Recruiting Manager', 348177, 'De-engineered dedicated monitoring', 3),
('Staff Scientist', 924032, 'Down-sized radical approach', 6),
('General Manager', 560361, 'Vision-oriented client-server infrastructure', 7),
('Pharmacist', 767791, 'Total zero tolerance core', 1),
('General Manager', 715656, 'Robust 24/7 benchmark', 9),
('Project Manager', 136663, 'Customizable bi-directional internet solution', 6),
('Research Associate', 493906, 'Visionary 5th generation intranet', 7),
('Systems Administrator II', 392970, 'Triple-buffered content-based moderator', 8),
('Cost Accountant', 387226, 'Sharable fault-tolerant neural-net', 7),
('Web Developer II', 684965, 'Decentralized needs-based algorithm', 5),
('Dental Hygienist', 522573, 'Enterprise-wide high-level collaboration', 2),
('Administrative Assistant III', 552894, 'Digitized reciprocal local area network', 7),
('Statistician IV', 498116, 'Innovative motivating paradigm', 2),
('Administrative Assistant I', 29235, 'Cross-group intermediate interface', 8),
('Environmental Specialist', 730164, 'Synergized reciprocal policy', 5),
('Operator', 253194, 'Mandatory attitude-oriented knowledge base', 1),
('Product Engineer', 255464, 'Compatible logistical artificial intelligence', 6),
('Technical Writer', 912030, 'Grass-roots even-keeled system engine', 4),
('Professor', 570792, 'Robust system-worthy benchmark', 8),
('Accounting Assistant IV', 735136, 'Vision-oriented foreground budgetary management', 8),
('Technical Writer', 599233, 'Business-focused web-enabled circuit', 2),
('Business Systems Development Analyst', 312147, 'Profit-focused responsive artificial intelligence', 1),
('Compensation Analyst', 554989, 'Switchable global policy', 6),
('Accounting Assistant III', 484756, 'Proactive contextually-based secured line', 8),
('Web Developer III', 246607, 'Right-sized transitional software', 3),
('Financial Analyst', 459983, 'Synergistic global capacity', 8),
('Senior Financial Analyst', 950586, 'Phased systematic neural-net', 2),
('Software Engineer II', 762626, 'Virtual human-resource infrastructure', 2),
('Staff Scientist', 106539, 'Adaptive upward-trending structure', 9),
('Actuary', 782353, 'Customer-focused background implementation', 2),
('Social Worker', 762368, 'Future-proofed optimal hierarchy', 4),
('Sales Associate', 948451, 'Proactive coherent process improvement', 8),
('Office Assistant IV', 111224, 'Advanced next generation conglomeration', 8),
('Physical Therapy Assistant', 606529, 'Sharable solution-oriented challenge', 4),
('Programmer I', 698777, 'Reduced incremental encryption', 9),
('Clinical Specialist', 368668, 'Seamless object-oriented interface', 1),
('Environmental Tech', 75626, 'Digitized interactive knowledge base', 2),
('Safety Technician I', 726013, 'Networked optimal process improvement', 7),
('Analog Circuit Design manager', 934656, 'Synergistic impactful productivity', 1),
('Chemical Engineer', 975776, 'Operative reciprocal solution', 7);

INSERT INTO employees (first_name, last_name, email, job_title)
VALUES
('Robin', 'Lindback', 'rlindback0@hud.gov', 2),
('Dorelia', 'Block', 'dblock1@godaddy.com', 8),
('Bethena', 'Brightie', 'bbrightie2@ameblo.jp', 3),
('Florenza', 'Yglesia', 'fyglesia3@canalblog.com', 6),
('Dela', 'Dudgeon', 'ddudgeon4@zimbio.com', 5),
('Blakeley', 'Southwell', 'bsouthwell5@ow.ly', 7),
('Halette', 'Minghi', 'hminghi6@hatena.ne.jp', 4),
('Mack', 'Fuzzey', 'mfuzzey7@fotki.com', 8),
('Boycie', 'Spieght', 'bspieght8@wikia.com', 5),
('Magdalen', 'Bestman', 'mbestman9@indiegogo.com', 8),
('Liana', 'Catonnet', 'lcatonneta@jimdo.com', 4),
('Deni', 'O''Cridigan', 'docridiganb@trellian.com', 8),
('Vivie', 'Aylwin', 'vaylwinc@is.gd', 9),
('Magda', 'Louthe', 'mlouthed@disqus.com', 3),
('Courtney', 'Mughal', 'cmughale@issuu.com', 9),
('Syman', 'Clutheram', 'sclutheramf@yandex.ru', 6),
('Anabal', 'Hapke', 'ahapkeg@prnewswire.com', 4),
('Kial', 'Beszant', 'kbeszanth@surveymonkey.com', 8),
('Annabella', 'Kenwrick', 'akenwricki@google.cn', 9),
('Erl', 'Tomasz', 'etomaszj@ycombinator.com', 4),
('Kinsley', 'Greenly', 'kgreenlyk@freewebs.com', 6),
('Kim', 'Stokes', 'kstokesl@epa.gov', 9),
('Benn', 'Coggeshall', 'bcoggeshallm@buzzfeed.com', 3),
('Aloisia', 'Ellum', 'aellumn@dot.gov', 2),
('Dawn', 'Tunkin', 'dtunkino@spotify.com', 8),
('Cris', 'Yewdale', 'cyewdalep@ow.ly', 3),
('Prent', 'Dundredge', 'pdundredgeq@freewebs.com', 5),
('Saleem', 'Fennelow', 'sfennelowr@wordpress.org', 9),
('Rozelle', 'Grigor', 'rgrigors@a8.net', 3),
('Christin', 'Cassar', 'ccassart@istockphoto.com', 4),
('Rem', 'Dundridge', 'rdundridgeu@gmpg.org', 9),
('Jacklyn', 'Rushmere', 'jrushmerev@si.edu', 5),
('Dorothee', 'Olner', 'dolnerw@pcworld.com', 4),
('Madalyn', 'Clymer', 'mclymerx@springer.com', 8),
('Tildy', 'Swoffer', 'tswoffery@myspace.com', 8),
('Benetta', 'Chiplin', 'bchiplinz@webmd.com', 2),
('Lorettalorna', 'Hadcock', 'lhadcock10@arizona.edu', 9),
('Warden', 'Gregol', 'wgregol11@mapy.cz', 1),
('Ilysa', 'Dumberell', 'idumberell12@wikia.com', 3),
('Moises', 'Bernadzki', 'mbernadzki13@ezinearticles.com', 5),
('Madalyn', 'Kike', 'mkike14@dedecms.com', 2),
('Kent', 'Itchingham', 'kitchingham15@imdb.com', 7),
('Chelsy', 'Corkish', 'ccorkish16@posterous.com', 2),
('Gwyneth', 'Tooting', 'gtooting17@usnews.com', 8),
('Wendel', 'Atmore', 'watmore18@google.it', 4),
('Cornall', 'Scholtz', 'cscholtz19@accuweather.com', 7),
('Nicolas', 'Walkling', 'nwalkling1a@gizmodo.com', 2),
('Dag', 'Adkins', 'dadkins1b@privacy.gov.au', 3),
('Almira', 'Blanche', 'ablanche1c@over-blog.com', 6),
('Dreddy', 'Kingcott', 'dkingcott1d@umich.edu', 8),
('Murial', 'Yakov', 'myakov1e@oakley.com', 1),
('Yettie', 'Suttell', 'ysuttell1f@qq.com', 1),
('Denise', 'Vayne', 'dvayne1g@springer.com', 6),
('Phillie', 'Kyneton', 'pkyneton1h@auda.org.au', 9),
('Charin', 'Cashley', 'ccashley1i@360.cn', 8),
('Aline', 'Gallichan', 'agallichan1j@wiley.com', 9),
('Dalt', 'Jowitt', 'djowitt1k@networksolutions.com', 3),
('Lil', 'Tokley', 'ltokley1l@house.gov', 5),
('Frederik', 'Degnen', 'fdegnen1m@merriam-webster.com', 1),
('Kittie', 'Forsaith', 'kforsaith1n@altervista.org', 4),
('Cate', 'Chiverstone', 'cchiverstone1o@dagondesign.com', 6),
('Etti', 'Pethybridge', 'epethybridge1p@ibm.com', 2),
('Daria', 'Borgars', 'dborgars1q@imageshack.us', 8),
('Wilhelmina', 'MacRanald', 'wmacranald1r@cbslocal.com', 2),
('Collin', 'Dade', 'cdade1s@cargocollective.com', 9),
('Augustine', 'Abrami', 'aabrami1t@washington.edu', 3),
('Herold', 'Hanby', 'hhanby1u@hexun.com', 8),
('Clemmie', 'Parmiter', 'cparmiter1v@mayoclinic.com', 3),
('Penelope', 'Patinkin', 'ppatinkin1w@illinois.edu', 1),
('Griselda', 'Scandrite', 'gscandrite1x@economist.com', 7),
('Clay', 'Overel', 'coverel1y@va.gov', 7),
('Tadeo', 'Towle', 'ttowle1z@gmpg.org', 2),
('Thadeus', 'Udey', 'tudey20@prweb.com', 3),
('Ariella', 'Atley', 'aatley21@alibaba.com', 2),
('Sharron', 'Benzing', 'sbenzing22@odnoklassniki.ru', 9),
('Tildi', 'd'' Elboux', 'tdelboux23@smugmug.com', 7),
('Neille', 'Lukins', 'nlukins24@ask.com', 3),
('Dennison', 'Leyre', 'dleyre25@ehow.com', 8),
('Ethelin', 'Hasslocher', 'ehasslocher26@prnewswire.com', 7),
('Ewart', 'Marten', 'emarten27@tinypic.com', 5),
('Rochette', 'Daggett', 'rdaggett28@flickr.com', 5),
('Drugi', 'Kermannes', 'dkermannes29@jugem.jp', 6),
('Chris', 'Woodroff', 'cwoodroff2a@facebook.com', 5),
('Denise', 'Priddle', 'dpriddle2b@goo.ne.jp', 3),
('Adey', 'Brayne', 'abrayne2c@telegraph.co.uk', 7),
('Vin', 'Cankett', 'vcankett2d@prlog.org', 7),
('Alejandro', 'Aujouanet', 'aaujouanet2e@theglobeandmail.com', 1),
('Sayres', 'Hazle', 'shazle2f@dagondesign.com', 8),
('Aurora', 'Kleehuhler', 'akleehuhler2g@joomla.org', 1),
('Haze', 'Golborn', 'hgolborn2h@huffingtonpost.com', 5),
('Hector', 'Maggiori', 'hmaggiori2i@nsw.gov.au', 3),
('Kiah', 'McDuffie', 'kmcduffie2j@cnbc.com', 1),
('Caesar', 'Walshe', 'cwalshe2k@ning.com', 3),
('Kakalina', 'Di Iorio', 'kdiiorio2l@mtv.com', 8),
('Martelle', 'Revan', 'mrevan2m@360.cn', 1),
('Francklyn', 'Blaisdell', 'fblaisdell2n@360.cn', 4),
('Buffy', 'Fern', 'bfern2o@house.gov', 1),
('Claudina', 'Mullan', 'cmullan2p@mtv.com', 6),
('Terza', 'Plowes', 'tplowes2q@mapquest.com', 6),
('Chev', 'O''Cannovane', 'cocannovane2r@netscape.com', 5),
('Sonnie', 'Peery', 'speery2s@fastcompany.com', 2),
('Marlow', 'Blasoni', 'mblasoni2t@eepurl.com', 1),
('Brade', 'Longfellow', 'blongfellow2u@nasa.gov', 6),
('Emile', 'Brozek', 'ebrozek2v@ft.com', 1),
('Gregorius', 'Lakeman', 'glakeman2w@wix.com', 8),
('Den', 'Sprasen', 'dsprasen2x@boston.com', 2),
('Elenore', 'Pickton', 'epickton2y@cdc.gov', 1),
('Arabel', 'Drummond', 'adrummond2z@stumbleupon.com', 3),
('Fran', 'Yushmanov', 'fyushmanov30@xrea.com', 2),
('Hamel', 'Sercombe', 'hsercombe31@dmoz.org', 2),
('Deane', 'Clowton', 'dclowton32@1und1.de', 1),
('Rosemary', 'Boriston', 'rboriston33@va.gov', 8),
('Emmeline', 'Blaxter', 'eblaxter34@howstuffworks.com', 3),
('Field', 'Churn', 'fchurn35@google.com.br', 6),
('Lyndy', 'Ren', 'lren36@noaa.gov', 4),
('Myranda', 'Eilers', 'meilers37@mashable.com', 3),
('Helena', 'Ivanyukov', 'hivanyukov38@fc2.com', 9),
('Margaret', 'Sturman', 'msturman39@alibaba.com', 5),
('Cecil', 'Jepperson', 'cjepperson3a@fc2.com', 6),
('Valera', 'Moffet', 'vmoffet3b@nydailynews.com', 9),
('Elenore', 'Seckington', 'eseckington3c@ebay.co.uk', 9),
('Hubie', 'Elden', 'helden3d@cafepress.com', 5),
('Gipsy', 'Clayal', 'gclayal3e@furl.net', 9),
('Waylin', 'Peak', 'wpeak3f@gov.uk', 9),
('Ruperto', 'Upfold', 'rupfold3g@walmart.com', 1),
('Israel', 'Plain', 'iplain3h@github.io', 2),
('Sadye', 'Weddeburn', 'sweddeburn3i@topsy.com', 4),
('Gail', 'McVicar', 'gmcvicar3j@sphinn.com', 3),
('Anatola', 'Adamiak', 'aadamiak3k@infoseek.co.jp', 7),
('Elvina', 'Adenet', 'eadenet3l@cam.ac.uk', 1),
('Guthrey', 'Wadge', 'gwadge3m@sourceforge.net', 3),
('Renaldo', 'Osmund', 'rosmund3n@icq.com', 7),
('Aldus', 'Somerscales', 'asomerscales3o@gravatar.com', 2),
('Prudy', 'Normanton', 'pnormanton3p@archive.org', 1),
('Gisela', 'Josofovitz', 'gjosofovitz3q@ovh.net', 5),
('Bobbee', 'Covotto', 'bcovotto3r@nba.com', 2),
('Keane', 'Shallcroff', 'kshallcroff3s@pbs.org', 7),
('Alphonso', 'Knudsen', 'aknudsen3t@networksolutions.com', 1),
('Gregg', 'Falconar', 'gfalconar3u@istockphoto.com', 1),
('Rabi', 'Boast', 'rboast3v@dyndns.org', 6),
('Latisha', 'Woodington', 'lwoodington3w@sogou.com', 7),
('Violetta', 'Cudihy', 'vcudihy3x@ameblo.jp', 2),
('Maddy', 'Pollett', 'mpollett3y@digg.com', 8),
('Gussy', 'Neubigging', 'gneubigging3z@spotify.com', 6),
('Mirilla', 'Ballchin', 'mballchin40@sina.com.cn', 5),
('Berkley', 'O''Mara', 'bomara41@hc360.com', 5),
('Denney', 'Sibbe', 'dsibbe42@usgs.gov', 7),
('Ruperta', 'Croisier', 'rcroisier43@bigcartel.com', 1),
('Valeda', 'Cattermoul', 'vcattermoul44@microsoft.com', 4),
('Rosita', 'Sandyford', 'rsandyford45@epa.gov', 8),
('Chet', 'McKelvie', 'cmckelvie46@google.fr', 7),
('Emerson', 'Cockrem', 'ecockrem47@time.com', 4),
('Wayland', 'Duck', 'wduck48@furl.net', 7),
('Eduardo', 'Fergyson', 'efergyson49@eventbrite.com', 2),
('Yolande', 'Sexon', 'ysexon4a@dell.com', 1),
('Nathalia', 'Leppard', 'nleppard4b@quantcast.com', 8),
('Garwin', 'Presswell', 'gpresswell4c@unicef.org', 3),
('Rabi', 'MacIver', 'rmaciver4d@bravesites.com', 2),
('Wolfy', 'Maxted', 'wmaxted4e@goo.ne.jp', 1),
('Sharona', 'Barnicott', 'sbarnicott4f@zdnet.com', 6),
('Claudine', 'Strover', 'cstrover4g@reverbnation.com', 8),
('Wylma', 'Yankishin', 'wyankishin4h@photobucket.com', 4),
('Joann', 'Busfield', 'jbusfield4i@npr.org', 6),
('Eadmund', 'Vann', 'evann4j@flavors.me', 7),
('Madalyn', 'O'' Byrne', 'mobyrne4k@soundcloud.com', 7),
('Shay', 'Ramsdale', 'sramsdale4l@gmpg.org', 1),
('Wilfred', 'Ciccarello', 'wciccarello4m@tripadvisor.com', 7),
('Valentijn', 'Tidy', 'vtidy4n@blogspot.com', 4),
('Roxy', 'Qusklay', 'rqusklay4o@cbslocal.com', 3),
('Daryl', 'Gossage', 'dgossage4p@geocities.com', 1),
('Matilda', 'Sawyer', 'msawyer4q@amazonaws.com', 9),
('Rebeca', 'Pointing', 'rpointing4r@sohu.com', 4),
('Terza', 'Spolton', 'tspolton4s@cam.ac.uk', 7),
('Constanta', 'Bassilashvili', 'cbassilashvili4t@naver.com', 8),
('Elliott', 'Pawsey', 'epawsey4u@noaa.gov', 9),
('Larisa', 'Scarlin', 'lscarlin4v@creativecommons.org', 4),
('Laurella', 'Meekings', 'lmeekings4w@exblog.jp', 9),
('Salome', 'Magnus', 'smagnus4x@mediafire.com', 8),
('Karol', 'Frensch', 'kfrensch4y@dyndns.org', 7),
('Damara', 'Jovicevic', 'djovicevic4z@hud.gov', 8),
('Ahmed', 'Caines', 'acaines50@unicef.org', 2),
('Darb', 'MacFayden', 'dmacfayden51@chron.com', 8),
('Gale', 'Breeder', 'gbreeder52@theglobeandmail.com', 4),
('Millisent', 'Swanton', 'mswanton53@google.ca', 1),
('Konstantin', 'Badam', 'kbadam54@prnewswire.com', 3),
('Mimi', 'Feaster', 'mfeaster55@godaddy.com', 2),
('Grantley', 'Huniwall', 'ghuniwall56@cloudflare.com', 6),
('Midge', 'Gorriessen', 'mgorriessen57@sina.com.cn', 4),
('Grantley', 'Rignoldes', 'grignoldes58@europa.eu', 6),
('Giacinta', 'D''Ambrogio', 'gdambrogio59@ted.com', 8),
('Nessi', 'Whiston', 'nwhiston5a@spotify.com', 4),
('Casie', 'Byrd', 'cbyrd5b@cisco.com', 2),
('Selinda', 'McClelland', 'smcclelland5c@mayoclinic.com', 4),
('George', 'O''Dooghaine', 'godooghaine5d@hc360.com', 3),
('Ange', 'Burrus', 'aburrus5e@samsung.com', 5),
('Mickey', 'Hatchell', 'mhatchell5f@51.la', 1),
('Ferd', 'Lumsdall', 'flumsdall5g@twitpic.com', 3),
('Shawn', 'Hulls', 'shulls5h@wiley.com', 8),
('Ewell', 'Knoble', 'eknoble5i@domainmarket.com', 1),
('Nancey', 'Stode', 'nstode5j@macromedia.com', 7);
